### PR TITLE
Add python 2, python 3 compatibility & Create "pygeppetto" root package

### PR DESCRIPTION
**Pull request by aranega**
I had a little time today so I modified the code as we discussed (see #8). With this pull request, pygeppetto:

* is compatible with Python 2 & 3 (the `pyecore` switch is done in the `setup.py`)
* includes `py3` in `tox`
* considers the `model` package as part of a root `pygeppetto` package

I also allowed myself to fix some code that could lead to issues in the `geppetto_factory` (mutable shared object as default parameter value in some methods). I hope that's ok with you.

### CODE REVIEW

**Comment by tarelli** [comment]
@aranega looks great, thanks! The only change I'd make is I'd move the geppetto_manager one level up to the pygeppetto package since it's a more generic entry point not model specific.

**Comment by tarelli** [comment]
@aranega "ui.py" too..if those will grow beyond just one module then we can create some other subpackages like model

**Comment by aranega** [comment]
@tarelli No problem! Indeed, `ui.py` and `geppetto_manager` would be better at the top level. I'm on it.

**Comment by aranega** [comment]
@tarelli While performing the modifications, I quickly look at the `geppetto_manager`, and I've the impression that the emerging architecture is very "Java-alike". Obviously I don't have all the details, but is the architecture "final"?

**Comment by tarelli** [comment]
@aranega no it's not final in any way and there's another branch where we started thinking about adding more interfaces but it's all still a work in progress. We could really use your help if you have a good sense for how to best port our Java API to pygeppetto, would you be up for a meeting just to discuss this? :)

**Comment by aranega** [comment]
@tarelli Sure, I can give you a hand (at my level of course, I'm no expert), and I can surely find some time to discuss about it.

**Comment by aranega** [comment]
If I got this right, @afonsobspinto is doing an awesome job to merge and deal with the Python 2/3 compatibility for pygeppetto (among other things), so this PR is not required anymore, I close it ;)

**Pull request closed without merging**
