### PR TITLE
Feature/python2 3 compatibility

### PR DESCRIPTION
**Pull request by tarelli**

### CODE REVIEW

**Comment by afonsobspinto** [comment]
Hey @aranega. I'm currently exploring this pull request and I saw some changes about metaclasses which broke the py2 tests. I [searched online](http://portingguide.readthedocs.io/en/latest/classes.html#metaclasses) and I read that the python 3 syntax is not compatible with python 2 without the use of a compatibility library called [six](https://pythonhosted.org/six/). What are your thoughts on matter? Should we import it? or do you have other plans?
I exposed this questions to @tarelli as well and he was the one who pointed me in your direction.

**Comment by aranega** [comment]
Hi @afonsobspinto, indeed the metaclass handling as changed on this PR, but the used syntax is Python 2/3 compatible using a class decorator `@EMetaclass` (it relies on the same principle that the one used by 'six') so you should not experience issues with the tests. 
I guess there is something in my side that is probably missing in yours (perhaps missing dependency, `tox` tests runs just fine for Python 2 and 3 in my side).

Did you use `tox` to run the tests or directly using `pytest`?  Could you post the stacktrace you have and the result of `pip freeze` and `python --version`? I hope this will give me more clues about what's going on.

Also, if you use `tox`, sometimes the `.tox` directory can be polluted by some old deps and stuffs, deleting it could perhaps solve this.

**Comment by afonsobspinto** [comment]
@aranega you were right. I'm using tox. Deleting its directory did the trick. All tests are successful now. Sorry to bother and thanks. :ok_hand:

**Comment by aranega** [comment]
@afonsobspinto Don't worry, I'm glad it was just a `.tox` issue ;)

**Pull request merged**
